# Generated by Django 5.2.10 on 2026-03-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_discipline_projectdiscipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('proposal', 'Project Proposal'), ('proposal_revision', 'Proposal Revision'), ('literature_review', 'Literature Review'), ('methodology', 'Methodology'), ('implementation', 'Implementation & Results'), ('final_document', 'Final Document')], max_length=32)),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='projects/stages/')),
                ('student_note', models.TextField(blank=True)),
                ('supervisor_feedback', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved')], default='pending', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_submissions', to='api.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stage_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('project', 'stage')},
            },
        ),
    ]
