# Generated by Django 5.2.10 on 2026-03-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projectstagesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='plagiarism_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='plagiarism_report_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/final/'),
        ),
        migrations.AddField(
            model_name='project',
            name='supporting_documents_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/final/'),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_status',
            field=models.CharField(choices=[('proposal_submitted', 'PROPOSAL_SUBMITTED'), ('proposal_approved', 'PROPOSAL_APPROVED'), ('proposal_rejected', 'PROPOSAL_REJECTED'), ('proposal_revision', 'PROPOSAL_REVISION'), ('in_progress', 'IN_PROGRESS'), ('interim_evaluated', 'INTERIM_EVALUATED'), ('final_submitted', 'FINAL_SUBMITTED'), ('plagiarism_flagged', 'PLAGIARISM_FLAGGED'), ('plagiarism_passed', 'PLAGIARISM_PASSED'), ('approved', 'APPROVED'), ('final_revision', 'FINAL_REVISION'), ('rejected', 'REJECTED'), ('archived', 'ARCHIVED')], default='proposal_submitted', max_length=32),
        ),
        migrations.CreateModel(
            name='InterimEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interim_evaluations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interim_evaluations', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDevelopmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('progress_report', 'Progress Report'), ('chapter', 'Chapter'), ('code', 'Code')], max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to='projects/development/')),
                ('comment', models.TextField(blank=True)),
                ('supervisor_comment', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='pending', max_length=24)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_submissions', to='api.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_development_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('proposal', 'Proposal'), ('final', 'Final')], max_length=16)),
                ('decision', models.CharField(choices=[('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('revision_required', 'REVISION_REQUIRED')], max_length=24)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.project')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
