# Generated by Django 5.2.10 on 2026-03-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workflow_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStageSubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='projects/stages/versions/')),
                ('student_note', models.TextField(blank=True)),
                ('supervisor_feedback', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved')], default='pending', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stage_submission_versions', to=settings.AUTH_USER_MODEL)),
                ('stage_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.projectstagesubmission')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('stage_submission', 'version')},
            },
        ),
    ]
