# Generated by Django 5.2.10 on 2026-03-19

from django.db import migrations, models


def remove_proposal_revision_stage(apps, schema_editor):
    ProjectStageSubmission = apps.get_model('api', 'ProjectStageSubmission')
    ProjectStageSubmission.objects.filter(stage='proposal_revision').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_projectstagesubmissionversion'),
    ]

    operations = [
        migrations.RunPython(remove_proposal_revision_stage, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projectstagesubmission',
            name='stage',
            field=models.CharField(
                choices=[
                    ('proposal', 'Project Proposal'),
                    ('literature_review', 'Literature Review'),
                    ('methodology', 'Methodology'),
                    ('implementation', 'Implementation & Results'),
                    ('final_document', 'Final Document'),
                ],
                max_length=32,
            ),
        ),
    ]
