# Generated by Django 5.2.10 on 2026-02-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_downloads_project_views_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.discipline')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=1.0)),
                ('is_primary', models.BooleanField(default=False)),
                ('tagged_by', models.CharField(choices=[('auto', 'Auto-detected'), ('manual', 'Manual')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.discipline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_tags', to='api.project')),
            ],
            options={
                'ordering': ['-relevance_score'],
                'unique_together': {('project', 'discipline')},
            },
        ),
    ]
